[server.pv.addon.broadcast]
broadcasting_specific = "Đang phát sóng cho %s"
broadcasting_wide = "Đang phát sóng toàn %s"

[server.pv.addon.broadcast.command]
world_set = "Đặt chế độ phát sóng thế giới thành %s"
world_usage = "Dùng: /vbroadcast world <tên thế giới>"
usage = "Dùng: /vbroadcast <range|server|world> <khoảng cách mong muốn | tên thế giới>"
server_set = "Đặt chế độ phát sóng server"
range_set = "Thiết lập phạm vi phát sóng %d"
range_usage = "Dùng: /vbroadcast range <số lớn hơn 0>"
[client.pv.activation]
broadcast = "Phát sóng"
